### PR TITLE
Fix: temp basal duration

### LINKED ISSUE #112: Temp basal duration
Currently, MedtrumKit (and DanaKit) does not consider the duration of a temp basal.

Meaning, if a user loses ble connection through the night and reconnects several hours later. The temp basal endtime always gets recorded as Date.now, while the duration might be much lower.

This needs to be fixed

### PR DESCRIPTION
**Pull request by bastiaanv**
Currently, the end date of a temp basal event is always Date.now, which is fine for 99% of the cases.
But when a user is disconnected (or runs open loop) for a duration long than the temp basal, the Date.now isn't fine anymore.

This PR changes this behaviour:
- It checks whether the temp basal is expired
- If not, nothing change
- If it did, it add the basal event after the temp basal and changes the endDate accordingly

(also had to update PatchLifetimeFormatting because the formatter wasn't happy while using the newer XCode 26.4)

### CODE REVIEW

**Comment by marionbarker** [comment]
## Test

❌ Basal events that should not be there (shows up at time of start of TBR)
❌ If a temp basal rate (TBR) should have ended, it should not be shown as continuing
❌ If a TBR completes while out of range, it should be assumed to have completed nominally after reconnecting - not discarded.

I'm not sure how the Omnipod pump managers handle this situation where TBR ends and there is signal loss wrt the pump.
Let's find out and do the same thing.

### Configuration

Build MedtrumKit commit 7b89b66, `fix/temp-basal-duration` onto a test phone
* iPhone SE 2nd gen running iOS 18.7.8
* pump: Medtrum
* CGM: Eversense Demo

Let system run nominally for a couple of hours. Then do a test.

### Start of Temp Basal

Note about the table - I did not record every event, just enough to see the pattern.
Note - some rows are recorded where the time is the same as the event time - so isMutable is true. Later the same event is reported after isMutable is false and the pump event is finalized.

The screenshot below shows the reported pump events. 
* The Basal events should not show up as events. (Return to scheduled basal is not a pump event).
* The TBR that completed while out of range of BLE should not vanish after signal loss is resolved.

| Time | Event Time | Event | auto | isMutable | units | delivered<br>Units | comment |
|:--|:--|:--|:--|:--|:--|:--|:--|
| 12:48 | 12:28 | Temp Basal | true | false | 0 | 0 | ✅ nominal behavior, completed TBR |
| 12:48 | 12:28 | Basal | nil | false | 1.2 | nil | ❌ not a pump event |
| 12:48 | 12:48 | Temp Basal | true | true | 0 | nil | ✅ nominal behavior for active TBR |
| 12:48 | 12:48 | Basal | nil | false | 1.2 | nil | ❌ not a pump event |
| 12:50 | - | - | - |  - | - | - | move Medtrum pump out of range |
| 15:23 | - | - | - |  - | - | - | check phone status <br> signal loss and previous 2 events are still the most recent events<br>screenshot on left |
| 15:23 | 12:48 | Temp Basal | true | true | 0 | nil | ❌ past time for TBR to complete<br>find out how pods handle this |
| 15:23 | 12:48 | Basal | nil | false | 1.2 | nil | ❌ not a pump event |
| 15:25 | - | - | - |  - | - | - | move Medtrum pump into range |
| 15:28 | - | - | - |  - | - | - | back to green loop (loop times were 15:28, 15:33, etc |
| 15:28 | 12:48 | Temp Basal | - | - | - | - | ❌ this record is no longer seen<br> last TBR reported is the one before this one<br>see screenshot on right - taken later |
| 15:28 | 12:48 | Basal | nil | false | 1.2 | nil | ❌ not a pump event  |
| - | - | - | - |  - | - | - | skip recording the boluses|
| 15:48 | 15:48 | Temp Basal | true | true | 0 | nil | ✅ nominal behavior for active TBR, wait for it to update |
| 15:48 | 15:48 | Basal | nil | false | 1.2 | nil | ❌ not a pump event  |
| 15:53 | 15:48 | Temp Basal | true | false | 0 | 0 | ✅ nominal behavior for completed TBR |
| 15:53 | 15:48 | Basal | nil | false | 1.2 | nil | ❌ not a pump event  |

#### Pump events screenshot

Note the TBR in progress when BLE connection is lost, is removed after connection is restored.

medtrumkit-pr118

File: MedtrumKitUI/ViewModels/Settings/MedtrumKitSettingsViewModel.swift [hunk 1]
```diff
@@ -119,6 +119,9 @@ class MedtrumKitSettingsViewModel: ObservableObject, PumpManagerStatusObserver,
         self.toPreviousPatchDetails = toPreviousPatchDetails
         self.toSettings = toSettings
         self.activatePatchAction = activatePatchAction
+        super.init()
+
+        super.init()
```
Comment (marionbarker) [inline MedtrumKitUI/ViewModels/Settings/MedtrumKitSettingsViewModel.swift]: Why are there 2 super.init()?

Comment (bastiaanv) [reply MedtrumKitUI/ViewModels/Settings/MedtrumKitSettingsViewModel.swift]: Mistake during merging. Sorry for that

**Comment by bastiaanv** [comment]
@marionbarker The PR has become much bigger than I anticipated.

What I changed in the last commit (4ce09d7):
- Migrated the basal state (several seperate properties in the state) to a single basalDose (UnfinalizedDose)
- This is the same mechanism OmniBLE uses:
  - A single property that contains whether the basal is suspended, active, tempBasal or resumed, including basal rates, starting times & durations)
  - This makes the PumpManager's code much cleaner, less properties to update

I am currently running Loop (https://github.com/marionbarker/LoopWorkspace.git branch: feat/add_all_managers) in the background, via my Nightscout cloud cgm & MedtrumKit simulator MacOS. Will be running this for a while. I think it is a good idea to do a full Pump Event test again, since the core has been changed that much

**Comment by marionbarker** [comment]
## Test

✅ The spurious Basal event intersperse between TBR is gone (which is good), but . . .
❌ The TBR that completed while the patch was out of range was discarded after BLE was restored.

Note - I confirmed that Omnipod code in the same situation finalizes the TBR as soon as BLE comms are restored.

### Configuration

Because PR #118 and #120 change some of the same files, I tested both together.
I started with dev, fix/temp-basal-duration and fix/deactivate-patch at commits 6c3a883, f4b3071, and 9b2fd93 respectively, then created a new branch and merged code from both PR:
```
 1009  git switch dev
 1010  git switch -c pr118_120
 1011  git merge fix/temp-basal-duration
 1012  git merge fix/deactivate-patch
```

Using this version of MedtrumKit, build Loop onto the test phone currently running a Medtrum patch.
* SE 2nd gen running iOS 18
* Pump: Medtrum
* CGM: Eversense 365 (using sensor in vial with glucose solution)
* Dosing Strategy: Temp Basal Only

### Bluetooth Connection Loss during TBR

Repeat TBR test from before.

| Time | Event Time | Event | auto | isMutable | units | delivered<br>Units | comment |
|:--|:--|:--|:--|:--|:--|:--|:--|
| 21:13 | 21:02:01 | Temp Basal | true | false | 1.55 | 0.1 | ✅ nominal, correct dose |
| 21:13 | 21:07:00 | Temp Basal | true | false | 2.7 | 0.2 | ✅ nominal, correct dose |
| 21:13 | 21:11:59 | Temp Basal | true | true | 3.0 | nil| ✅ nominal behavior for active TBR |
| 21:23 | 21:11:59 | Temp Basal | true | true | 3.0 | nil| ✅ nominal behavior for active TBR<br>end date if not interrupted is 21:41:59 |
| 21:23 | - | - | - |  - | - | - | move Medtrum pump out of range |
| 21:29 | - | - | - |  - | - | - | Medtrum UI shows disconnected, main screen yellow Loop |
| 21:38 | - | - | - |  - | - | - | Medtrum UI shows disconnected, main screen red Loop |
| 21:40 | - | - | - |  - | - | - | Medtrum UI shows disconnected,  main screen red Loop & pump signal loss |
| 21:43 | 21:11:59 | Temp Basal | true | true | 3.0 | nil| ✅ nominal behavior for TBR that has not been finalized<br>end date was 21:41:59<br>❓ might want to have basal display on Medtrum UI say Unknown instead of 3.0 U/hr |
| 21:46 | - | - | - |  - | - | - | move Medtrum pump into range |
| 21:46  | - | - | - |  - | - | - |  Medtrum UI shows connected and basal rate shows as scheduled 1.2, green loop |
| 21:47 | 21:11:59 | Temp Basal | true | true | 3.0 | nil | ❌ has not finalized yet |
| 21:51 | 21:11:59 | Temp Basal | - | - | - | - | ❌ TBR of 3 U/hr for 30 minutes vanishes when next TBR is set |
| 21:51 | 21:51:54 | Temp Basal | true | true | 1.8 | nil | ✅ nominal behavior for active TBR |

#### Screenshot

The screenshots below show the 3.0 U/hr TBR that completed while patch was out of range was discarded after patch returned.

medtrum-pr118-almost

**Comment by bastiaanv** [comment]
@marionbarker Are you certain that the merge of both PR's was done correctly?

I am unable to recreate your issue, but I do not know if that is because I am running the MedtrumKit simulator instead of the real pump.

My setup:
- Nightscout Remote CGM
- Unified Pump Manager - MedtrumKit
- SHA: [f4b3071](https://github.com/jbr7rr/MedtrumKit/pull/118/commits/f4b307180c8455690443a16fba6c2e354ab8c8a2)
  - Made small edit to above sha -> Force TBR to 5min
- Dosing Strategy: Temp Basal Only

## Table
| Time | Event Time | Event | auto | isMutable | units | delivered<br>Units | comment |
|:--|:--|:--|:--|:--|:--|:--|:--|
| 20:49 | 20:49:15 | Temp Basal | true | true | 0.0 | nil | ✅ correct TBR (note, forced duration of 5 min) |
| 20:49 | - | - | - | - | - | - | Killed Simulator |
| 20:56 | - | - | - | - | - | - | Medtrum UI shows disconnected, Loop shows yellow, TBR expired but not shown in Medtrum UI |
| 20:57 | - | - | - | - | - | - | Started Simulator |
| 20:57 | 20:49:15 | Temp Basal | true | true | 0.0 | nil | ❓ Reconnected, but waiting for next Loop cycle |
| 20:59 | 20:49:15 | Temp Basal | true | false | 0.0 | 0.0 | ✅ TBR finalized |
| 20:59 | 20:54:15 | Basal | true | false | 2.1 | nil | ✅ Basal added to fill the gap |
| 20:59 | 21:02:01 | Temp Basal | true | true | 0.0 | nil | ✅ New TBR for next cycle |

## Screenshots
| Event | Time | Screenshot |
|:--|:--|:--|
| Unfinalized TBR | 20:49 | IMG_1588 |
| Reconnected & next cycle done | 20:59 | IMG_1590 |
| Finalized TBR | 20:59 | IMG_1591 |
| Added Basal | 20:59 | IMG_1592 |
| Next TBR for next cycle | 20:59 | IMG_1593 |

**Comment by marionbarker** [comment]
I will repeat the test with both a simulator and a real patch pump. And I will test each PR independently to make sure I did not mess anything up.

Great idea to tweak the temp basal duration to 5 minutes.

**Comment by marionbarker** [comment]
## Test

✅ Success - when patch is removed from BLE and then returned after TBR completes, it is correctly reported.
❓ Not part of this PR, but I think the Signal Loss should be more prominent on the Medtrum Nano UI screen.

### Configuration

* iPhone SE 2nd gen, iOS 18.7
* Pump: Use the patch attached when testing PR #120 
* CGM: Eversense 365 Demo using (reports semi-random numbers but also provides heartbeat)
* switch to Medtrum bastiaanv:fix/temp-basal-duration, commit f4b3071
* Clean build folder, close workspace, reopen and build
* Dosing strategy is Temp Basal Only
* Therapy value did have target of 180 to 180 when trying to save insulin overnight
   * Modify this to 90 to 90 so we will get some TBR commanded

### Test Narrative

wait for TBR to start then remove patch from BLE range until TBR ends, then return it.

| Time | Event Time | Event | auto | isMutable | units | delivered<br>Units | comment |
|:--|:--|:--|:--|:--|:--|:--|:--|
| 17:12 | 17:12:18<br>17:42:18 | Temp Basal | true | true | 3.0 | nil| ✅ nominal behavior for active TBR |
| 17:13 | - | - | - | - | - | - | move Medtrum pump out of range |
| 17:22 | - | - | - | - | - | - | Loop main screen: yellow loop<br>Medtrum UI: 3 U/hr and disconnected |
| 17:37 | - | - | - | - | - | - | Loop main screen: red loop & Signal Loss<br>Medtrum UI: 3 U/hr and disconnected |
| 17:46 | 17:12:18<br>17:42:18| Temp Basal | true | true | 3.0 | nil | Loop main screen: red loop & Signal Loss & TBR plot returns to scheduled basal<br>Medtrum UI: 3 U/hr and disconnected |
| 17:50 | - | - | - | - | - | - | move Medtrum pump back into range |
| 17:50 |  - | - | - | - | - | - |  Loop main screen: red loop & Signal Loss & TBR plot returns to scheduled basal<br>Medtrum UI: 3 U/hr and **connected** |
| 17:53 | 17:12:18<br>17:42:18| Temp Basal | true | false | 3.0 | 1.5 | ✅ nominal, correct dose |
| 17:42 | 17:42:18 | Basal | nil | false | 1.2 | nil | returned to scheduled basal
| 17:52 | 17:52:22<br>18:22:22 | Temp Basal | true | true | 3.0 | nil| ✅ nominal behavior for active TBR |

#### Screenshot

medtrum-pr118-success

**Review by marionbarker — APPROVED** [review]
Approve from test

**Comment by marionbarker** [comment]
I let this run while doing other things. And it seems like the TBR is updated every 5 minutes.

I thought Loop only updated the TBR after 20 minutes if the TBR rate is unchanged. (To save batteries for pods and Medtronic pumps).

I guess since Medtrum always stays connected, changing TBR every 5 minutes is not a big deal. Just wanted to make sure this is intended.

medtrum-pr118-question

**Comment by bastiaanv** [comment]
@marionbarker Thank you for re-testing!
I will merge this tonight and sync PR #120 from dev.

Will be extra careful with merge based on your earlier comment:
```
 1009  git switch dev
 1010  git switch -c pr118_120
 1011  git merge fix/temp-basal-duration
 1012  git merge fix/deactivate-patch
```
