### PR TITLE
fix: update UI to match OmniPod better

### LINKED ISSUE #84: Align Patch Lifetime and Expiring Indication in UI across Pump Drivers
MedtrumKit currently has an inconsistency between different pump lifetime modes; normal and extended. 

For normal, the expiration is counting down from 80 hrs (3d 8h), for extended it is counting upward and has a slightly different hourglass icon (which is fine). 

Another inconsistency between Omnipod and Medtrum expiry display is the overall lifetime. For Omnipod, lifetime starts counting down at 72 hrs, so normal use, excluding grace periods. 

To align this with Omnipod displays (which the overwhelming majority of users on iOS uses), I propose the following two changes:
1. have both normal and extended mode display a count down; not a count up
2. display the actual use lifetime excluding grace period: for normal mode 72 hrs, for extended mode 112 hrs. At 120 hrs it will display the "basal only" message anyways that was introduced with #74 

(ping @bastiaanv as discussed :) )

### LINKED ISSUE #89: Missing Suspend Event when Forcefully Removing Patch
I had to quickly remove a patch and because of it, I forgot to deactivate it in the AID app before pulling the pump base from the old patch.

Subsequently, I had to force remove the old patch when deactivating before I could pair a new patch. 

History now is a missing a pump suspend event, and there is only a pump resume that was posted when the new patch was paired and activated. This will lead to faulty behavior for IOB calculation and must be addressed. 

Image

### LINKED ISSUE #91: "Extended patch expired" after 3 days 8 hours
I think this message was supposed to be displayed after 5 days, right?

It was very confusing - I saw this message instead of the patch age progress bar, thinking "it can't be 5 days already!". (had to do some manual datetime arithmetic)

image

image

/cc @bastiaanv

### PR DESCRIPTION
**Pull request by bastiaanv**
This PR updates the UI elements to match the omnipod better, also added the `No delivery after` in Patch information

Closes #84, closes #89

## Grace period

Graceperiod

## Expired (left normal, right extended mode)

True expired

true expired extended mode

tagging: @dnzxy , @marionbarker

### CODE REVIEW

File: MedtrumKitUI/Views/Settings/MedtrumKitSettings.swift [hunk 1]
```diff
@@ -57,6 +57,16 @@ struct MedtrumKitSettings: View {
                             .font(Font.footnote.weight(.semibold))
                     }.padding(.vertical, 8)
                 }
+
+                if viewModel.patchLifecycleState == .gracePeriod {
+                    VStack(alignment: .leading, spacing: 4) {
+                        Text(String(format: LocalizedString(
+                            "Change your Patch now.Insulin delivery will stop in %1$@ or when no more insulin remains.",
```
Comment (dnzxy) [inline MedtrumKitUI/Views/Settings/MedtrumKitSettings.swift]: Typo here, missing whitespace after first sentence / before `Insulin`.

**Review by dnzxy — APPROVED** [review]
Small typo, rest look good. 
Thank you for making these changes.

File: MedtrumKitUI/Views/Settings/MedtrumKitSettings.swift [hunk 2]
```diff
@@ -241,18 +251,24 @@ struct MedtrumKitSettings: View {
                         .foregroundColor(.secondary)
                 }
                 HStack {
-                    Text(LocalizedString("Patch ID", comment: "Text for activatedAt"))
+                    Text(LocalizedString("Activated at", comment: "Text for activatedAt"))
```
Comment (marionbarker) [inline MedtrumKitUI/Views/Settings/MedtrumKitSettings.swift]: OmnipodKit uses: "Activation"

`FrameworkLocalText("Activation", comment: "Label for Activation row")`

File: MedtrumKitUI/Views/Settings/MedtrumKitSettings.swift [hunk 3]
```diff
@@ -241,18 +251,24 @@ struct MedtrumKitSettings: View {
...
+                            .foregroundColor(.secondary)
+                            .multilineTextAlignment(.trailing)
+                    } else {
+                        Text("-")
+                            .foregroundColor(.secondary)
+                    }
                 }
                 HStack {
-                    Text(LocalizedString("Patch activated at", comment: "Text for activatedAt"))
+                    Text(LocalizedString("Expires at", comment: "Text for expiresAt"))
```
Comment (marionbarker) [inline MedtrumKitUI/Views/Settings/MedtrumKitSettings.swift]: OmnipodKit uses "Expiration"

`FrameworkLocalText("Expiration", comment: "Label for Expiration row")`

See this section of code for the Activation, Expiration and No Delivery/Faulted display:
https://github.com/loopandlearn/OmnipodKit/blob/main/OmnipodKit/PumpManagerUI/Views/OmniSettingsView.swift#L422-L449

File: MedtrumKitUI/Views/Settings/MedtrumKitSettings.swift [hunk 4]
```diff
@@ -261,7 +277,7 @@ struct MedtrumKitSettings: View {
                     }
                 }
                 HStack {
-                    Text(LocalizedString("Patch expires at", comment: "Text for expiresAt"))
+                    Text(LocalizedString("No delivery after", comment: "Text for expiresAt"))
```
Comment (marionbarker) [inline MedtrumKitUI/Views/Settings/MedtrumKitSettings.swift]: OmnipodKit uses "No Delivery" which is modified to "Faulted" if a pod faults and consequently delivery happens sooner.

`FrameworkLocalText("No Delivery", comment: "Label for No Delivery row")`

**Review by marionbarker — CHANGES_REQUESTED** [review]
Code review comments provided. Will provide test comments separately.

**Comment by marionbarker** [comment]
I did a test and grabbed screen shots but haven't had time to write up a nice report.

## Issues

There are two problems:

1. The top timeline numbers are not consistent with the idea of expiration 8 hours before no delivery time
2. When the patch settings are 72+8 hour grace when activating the patch and you later change the settings to extended (112 hrs until expire with 8 hours grace), the view on the main screen does not update. The converse is also true.  The settings must be changed and then a new patch activated to get the display to change.

## Screenshots

#### Nominal setting selected when patch activated.
 
medtrum-pr88-nominal

#### Extended setting selected when patch activated

medtrum-pr88-extended

**Comment by bastiaanv** [comment]
Processed all above feedback. Based on Marions screenshot, I also added that the minute part will be hidden if expires in is >24h

**Comment by marionbarker** [comment]
## Test with Loop

Two items to fix:
* When choosing extended life, the warning should show up before the change is saved
* There is no need for seconds in the Activation, Expiration or No Delivery lines

Observed a difference - the current version displays a Patch ID. The new version does not. Not sure if that is important.

Nice to have - put some information into Patch Details screen to remove from Nano Screen.

### Configuration

Use local clone for LoopKit/LoopWorkspace branches feat/dev-dana-medtrum and feat/eversense.
Update MedtrumKit to 3c27f7d

* iPhone SE 3rd gen, iOS 26.3

Build and attach MedtrumKit

Update to feat/fix-ui, commit a7b1f31

### Screenshot

Graphic below shows 
* Left side: TouchCare Nano 200 screen with the current version of dev
* Right side: TouchCare Nano 200 screen with the PR code

medtrum-pr88-updated

### Comments on state of PR

#### Completed Tasks

* Use the expected lifetime of either 80 hours or 120 hours and indicate expiration will happen 8 hours before that.
* Show lines with activation, expiration and no delivery times
   * ❓ I do not think the seconds should be included (OmnipodKit uses date at HH:MM only)

#### Tasks to Complete

Items I think are wrong are noted below.

* Not shown, but when I switch patch settings to extended (120 hours)
   * ✅ Expires in changes from  2 days 23 hours to 4 days 15 hour (correct)
   * ✅ Expiration changes from Mar 21, 2026 at 09:09:29 to Mar 23, 2026 at 01:09:29
   * ❌, ✅ , ✅  No Delivery unchanged from Mar 21, 2026 at 17:09:29 < repeated this 2 more times and it did not get reproduced (wondering if it was an SE display issue where rows are not always updated)

❌ When switching to the Extended Life, the warning does not show up until you save the setting, leave the screen and then return to the Patch settings screen.

Some patch details could be shown in a Patch Details screen similar to the way Omnipod display works, but this could wait for another PR.

### Test with extended time when activating

Deactivate the patch and remove brain. 
Configure to use extended time.
Connect brain to patch
Pair, prime and insert the patch again (as if new).
**Only do this on the test set-up, never while patch is attached to your body**

new activation time is 09:54
* ✅ the No Delivery line is correct: Mar 23, 2026 at 09:54

Modify patch settings back to nominal life.
* ✅ the No Delivery line updates correctly: Mar 21, 2026 at 17:54

Modify patch settings back to extended life
* ✅ the No Delivery line is correct: Mar 23, 2026 at 09:54

### Repeat test with nominal patch life

new activation time is 10:02
* ✅ the No Delivery line is correct: Mar 21, 2026 at 18:02

Modify patch settings to extended life
* ✅ the No Delivery line did update correctly: Mar 23, 2026 at 10:02

### Delete pump and repeat test

Deactivate patch
Delete pump
Add pump simulator
Delete pump simulator
Add Medtrum Nano

could not find base
* toggle bluetooth - same
* reboot phone - now connects to patch (this is a separate Issue #86)

Start Medtrum pump manager with the nominal expiration of 72 hours with grace period of 8 hour.
* Activation Mar 18 10:18
* Expiration Mar 21 10:18
* ✅No Delivery Mar 21 18:18

Modify the Patch Settings to extended time.
* Activation Mar 18 10:18
* Expiration Mar 23 2:18
* ✅ No Delivery: Mar 23 20:28

**Comment by bastiaanv** [comment]
- ❓(unable to reproduce) -> When choosing extended life, the warning should show up before the change is saved
- ✅ -> There is no need for seconds in the Activation, Expiration or No Delivery lines 
- ✅ -> Moved patch details & previous patch details to seperate screens
- ✅ -> Renamed Medtrum menu header from "TouchCare Nano xxxU" to "Medtrum Nano xxxU"

Edit: included fix for #89

**Comment by marionbarker** [comment]
## Narrative

I got distracted testing and forgot to come back after priming
* The patch was beeping at me when I returned several hours later
* It is likely that I waited too long to activate and this would never have worked
* However, I accidentally hit `Go back to priming` and it seemed to accept it
* But it left me in the Patch activation screen; where Activate gives an error
* Timestamp is around 2026-03-18 12:55 local (PDT)

### Configuration

rebuild with the latest commit, ec81154
* shows signal loss for pump

Start over with the patch as if new.

* Go back to pump base, add pump base to patch
* Tap on continue and it went through multiple screens to Patch Activation
* Tap on go back to priming
* Priming started nominally
* Got distrated again but only for a few minutes
* The medtrum manager progressed to showing patch as activated - even though I had not inserted needle after priming nor had I tapped the Activate button

At 13:19 on 2026-03-18, insert needle.

I like the patch details and previous patch details.

I don't have time for a lot of testing right now.

I suspect the failure to show the extended life warning is a problem with the SE phone. We have a lot of cases on the SE where a screen does not update until you exit and reenter the screen.

I noticed the patch time is 16:14, last checked at 13:18 and phone time is currently 13:22.
* tap on manually sync time
* it is saying patch has a fault
* deactivate the patch and remove brain from patch

Here's the Medtrum log for today, in case there is anything useful to glean from it.

[20260318_medtrumkit_log.txt](https://github.com/user-attachments/files/26098792/20260318_medtrumkit_log.txt)

**Comment by bastiaanv** [comment]
The prime of 13:19 was extremely slow. It started at 13:05:10 and continued till 13:11:35, a full 6 minutes. After which the patch was in state 99 -> fault. The faulty state explains why it skipped the activation state, since no activation is possible at this point.

Regarding the patch time, since it did not complete the activation flow, it skipped the time sync. This is done after the activation, together with setting the basal schedule.

I sadly cannot see what happened during the first priming. The driver did not receive any status updates after the prime was completed

**Comment by marionbarker** [comment]
## Test

I noticed a new commit landed after I built for my last test.
✅ Nominal test

This test was performed on 2026-03-19 in the afternoon PDT.

### Configuration

* Update the local clone version of MedtrumKit: ec81154..483015a
* Clean product build folder, restart xcode
* Rebuild onto Loop phone that is sitting with No Patch showing
* Check the LoopReport to ensure MedtrumKit commit is 483015a

### Test the right way

* wait until on the Patch priming screen to add the brain
* insert the clip so you can depress the needle part way before priming
* now reach the activate screen
* remove clip and tap on activate

All the rows appear nominal
* Change patch setting and graphic at top showing expires and row for Expiration and No Delivery update appropriately.

### Test insulin commands

Manual bolus shows isMutable true while happening, false when completed
Test that can cancel bolus while in progress
* see interrupted bolus 0.15 of 1 U

Loop is configured for automatic bolus. Let the patch run for an hour.
CMG is simulator running sine wave of 110 +/- 130 and is on the rise (at 136).
* 18:00 enter 45 g with no manual bolus and check history later.

NOTE - posting this work-in-progress test
I will come back to it later to report history with the automatic bolus - but I've tested that before.


### Test Mistakes - TL;DR

some of this includes user error

1. Tap on No Patch
2. Pump base settings screen shows current brain SN
3. Attach brain to patch, listen for beep-beep-beep and tap continue
4. Get unknown error: invalidResponse (code 8)

I suspect this is a reuse the patch issue - try these steps to **Clear Patch**
* remove the brain
* go back
* quit the app
* cycle Bluetooth on phone
* restart Loop

Go back to step 1 again and at step 4 it begins to prime.
Skipped the activate screen and is showing a fault.

I suspect this is a reuse the patch problem again:

Deactivate the patch and remove the brain.
Delete the Medtrum pump manager.
Add simulated pump to make sure pump manager got cleared

May have been user error
* wait until on the Patch priming screen to add the brain
* insert the clip so you can depress the needle part way before priming
* when I did things in the correct order they seemed to work

**Review by marionbarker — APPROVED** [review]
Approve by test.
