### PR TITLE
small changes

### LINKED ISSUE #26: Insulin usage history
It would be great if there is info in pump manager for total used insulin since activation of the current patch, total used insulin by previous patch and how many days and hours previous patch was active.

### LINKED ISSUE #28: Missing bolus progress/completion notifications
I enacted a 3-unit bolus in iAPS. The bolus progress went up to 2.1 and then stopped.

According to the subsequent reservoir reading - the bolus seems to have been fully delivered.

```
# 3-unit bolus here
[2025-09-29T02:47:36+0200 INFO] MedtrumPumpManager.swift - enactBolus(units:activationType:completion:)#286: Enact bolus - 3.0U, 180.0sec


[2025-09-29T02:47:36+0200 DEBUG] PeripheralManager.swift - writePacket(_:)#61: Writing data: 09130600013c0000b100
[2025-09-29T02:47:37+0200 DEBUG] PeripheralManager.swift - peripheral(_:didUpdateValueFor:error:)#330: Got data: 0f130600000016008500a87c16167900
[2025-09-29T02:47:38+0200 DEBUG] PeripheralManager.swift - peripheral(_:didUpdateValueFor:error:)#313: READ -> Got data: 2022100002004c0e0000000000
[2025-09-29T02:47:38+0200 INFO] PeripheralManager.swift - parseStateUpdate(_:)#219: State update: {"activeAlarms":[],"state":32,"reservoir":183,"bolus":{"type":0,"delivered":0.1,"completed":false}}
[2025-09-29T02:47:42+0200 DEBUG] PeripheralManager.swift - peripheral(_:didUpdateValueFor:error:)#313: READ -> Got data: 2022100004004a0e0000000000
[2025-09-29T02:47:42+0200 INFO] PeripheralManager.swift - parseStateUpdate(_:)#219: State update: {"reservoir":182.9,"bolus":{"completed":false,"type":0,"delivered":0.2},"activeAlarms":[],"state":32}
[2025-09-29T02:47:46+0200 DEBUG] PeripheralManager.swift - peripheral(_:didUpdateValueFor:error:)#313: READ -> Got data: 202210000600480e0000000000
[2025-09-29T02:47:46+0200 INFO] PeripheralManager.swift - parseStateUpdate(_:)#219: State update: {"activeAlarms":[],"reservoir":182.8,"state":32,"bolus":{"completed":false,"type":0,"delivered":0.30000000000000004}}
[2025-09-29T02:47:50+0200 DEBUG] PeripheralManager.swift - peripheral(_:didUpdateValueFor:error:)#313: READ -> Got data: 202210000800460e0000000000
[2025-09-29T02:47:50+0200 INFO] PeripheralManager.swift - parseStateUpdate(_:)#219: State update: {"activeAlarms":[],"reservoir":182.70000000000002,"bolus":{"delivered":0.4,"type":0,"completed":false},"state":32}
[2025-09-29T02:47:54+0200 DEBUG] PeripheralManager.swift - peripheral(_:didUpdateValueFor:error:)#313: READ -> Got data: 202210000a00440e0000000000

# ... more progress messages with 0.1 step

[2025-09-29T02:48:51+0200 INFO] PeripheralManager.swift - parseStateUpdate(_:)#219: State update: {"activeAlarms":[],"state":32,"bolus":{"completed":false,"type":0,"delivered":1.8},"reservoir":181.20000000000002}
[2025-09-29T02:48:55+0200 DEBUG] PeripheralManager.swift - peripheral(_:didUpdateValueFor:error:)#313: READ -> Got data: 202210002600260e0000000000
[2025-09-29T02:48:55+0200 INFO] PeripheralManager.swift - parseStateUpdate(_:)#219: State update: {"reservoir":181.10000000000002,"bolus":{"type":0,"delivered":1.9000000000000001,"completed":false},"state":32,"activeAlarms":[]}
[2025-09-29T02:48:59+0200 DEBUG] PeripheralManager.swift - peripheral(_:didUpdateValueFor:error:)#313: READ -> Got data: 202210002800240e0000000000
[2025-09-29T02:48:59+0200 INFO] PeripheralManager.swift - parseStateUpdate(_:)#219: State update: {"reservoir":181,"state":32,"activeAlarms":[],"bolus":{"type":0,"completed":false,"delivered":2}}
[2025-09-29T02:49:03+0200 DEBUG] PeripheralManager.swift - peripheral(_:didUpdateValueFor:error:)#313: READ -> Got data: 202210002a00220e0000000000


# last bolus progress here: 
[2025-09-29T02:49:03+0200 INFO] PeripheralManager.swift - parseStateUpdate(_:)#219: State update: {"reservoir":180.9,"state":32,"activeAlarms":[],"bolus":{"delivered":2.1,"completed":false,"type":0}}


[2025-09-29T02:49:13+0200 INFO] BluetoothManager.swift - centralManager(_:didDisconnectPeripheral:error:)#260: Device disconnected, name: MT
[2025-09-29T02:50:44+0200 WARNING] MedtrumPumpManager.swift - ensureCurrentPumpData(completion:)#190: Skipping status update -> data is fresh: 101.02488303184509 sec


# a minute later I hit the cancel button in iAPS because it was stuck in the "bolus-in-progress" state
[2025-09-29T02:51:56+0200 INFO] MedtrumPumpManager.swift - cancelBolus(completion:)#359: Cancelling bolus...

...
# a few message later:
[2025-09-29T02:51:59+0200 INFO] PeripheralManager.swift - parseStateUpdate(_:)#219: State update: {"battery":{"voltageB":2.80078125,"voltageA":6.083984375},"startTime":780796091,"storage":{"patchId":133,"sequence":22},"basal":{"type":6,"patchId":133,"sequence":21,"startTime":780799554,"rate":7,"delivery":0.6000000000000001},"patchAge":4511,"activeAlarms":[],"magnetoPlacement":3601,"state":32,"bolus":{"type":0,"completed":true,"delivered":3},"reservoir":179.70000000000002}
```

### PR DESCRIPTION
**Pull request by bastiaanv**
fixes for the following issues:
- #28 
- #26

### CODE REVIEW

File: MedtrumKitUI/Views/Settings/MedtrumKitSettings.swift [hunk 1]
```diff
@@ -264,6 +264,15 @@ struct MedtrumKitSettings: View {
                         Text(viewModel.batteryText(for: previousPatch.battery))
                             .foregroundColor(.secondary)
                     }
+                    if let reservoirLevel = previousPatch.reservoirLevel, let maxInsulin = previousPatch.maxInsulin {
+                        HStack {
+                            Text(LocalizedString("Insulin used", comment: "Text for Insulin used"))
+                                .foregroundColor(Color.primary)
+                            Spacer()
+                            Text(viewModel.reservoirText(for: Double(maxInsulin) - reservoirLevel))
```
Comment (yurique) [inline MedtrumKitUI/Views/Settings/MedtrumKitSettings.swift:272]: this might be somewhat inaccurate - after filling the pump with 200 units of insulin and activating it, I don't think I ever seen reservoir=200

also people might be filling the patch with less than max units

Comment (yurique) [reply MedtrumKitUI/Views/Settings/MedtrumKitSettings.swift:272]: maybe it's better to capture the initial reservoir value after patch activation? (and the final value before deactivation)

Comment (yurique) [reply MedtrumKitUI/Views/Settings/MedtrumKitSettings.swift:272]: @bastiaanv ☝️
